### ISSUE TITLE
Error while trying to get an output

### ISSUE THREAD

**Issue by fantapereira** [zevenet/zevenet-nagios-plugins#1] opened 2018-01-17 11:31 UTC
Hello, i have the following error trying to run the script via CM. I'm running NagiosXI on a CentOS 6.9 Server (VM provided by Nagios).

`[root@nagios libexec]# perl check_zevenet_cpu.pl  -H serverip -z 6DH2xE0yTiioiZrM -c10 -w20
Can't use an undefined value as filehandle reference at check_zevenet_cpu.pl line 179.
`

Line 179 is 
`# Starts the actual request

$retcode = $curl->perform;
`

could you please assist?

Thanks!

**Comment by emiliocampos-zevenet** [comment] 2018-01-17 12:07
Zevenet Nagios plugins only is supported for Zevenet Enterprise not Community, it will be supported in next release zevenet 5 community edition, released next month. 

Could you let us know what zevenet version are you running. 

Thanks!

**Comment by fantapereira** [comment] 2018-01-17 12:08
I'm running the enterprise Version. I was successfully genereated the zapi key

**Comment by emiliocampos-zevenet** [comment] 2018-01-17 13:52
Hi, I can confirm the check_zevenet_cpu.pl works properly, see output:

root@server:/zevenet-nagios-plugins/libexec# ./check_zevenet_cpu.pl -H 192.168.100.123 -z asdfl9io3dk -c90:100 -w40:50
ZEVENET_CPU WARNING - Zevenet ADC Load Balancer CPU usage is 0 % (100 % idle) | Idle=100%;4050;90100 IOWait=0%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=0%;; Usage=0%;; User=0%;; Total=100%;;

googling you can see that the error message is related to curl module perl. 

Can't use an undefined value as filehandle reference at

My current version is
libwww-curl-perl                      4.17-4

Could you check your libcurl installed version for perl? 

I think we could solve your issue but we would require more time in order to modify all the source code. 

Regards

**Comment by fantapereira** [comment] 2018-01-17 14:02
Thanks for the quick response. my Curl version is

`[root@nagios libexec]# curl -V
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
[root@nagios libexec]# curl-config --version
libcurl 7.19.7
`

**Comment by emiliocampos-zevenet** [comment] 2018-01-17 14:05
Dear this is the command line appilcation, I am doing reference to curl library for perl, they are different versions, if you are running Centos try with:

rpm -qa | grep curl

**Comment by fantapereira** [comment] 2018-01-17 14:09
sorry.. here is the output

`[root@nagios libexec]# rpm -qa | grep curl
python-pycurl-7.19.0-9.el6.x86_64
libcurl-7.19.7-53.el6_9.x86_64
curl-7.19.7-53.el6_9.x86_64
libcurl-devel-7.19.7-53.el6_9.x86_64
`

**Comment by emiliocampos-zevenet** [comment] 2018-01-17 14:40
[check_zevenet_cpu.pl.zip](https://github.com/zevenet/zevenet-nagios-plugins/files/1639348/check_zevenet_cpu.pl.zip)


See my attached zip file and use it I have done some modifications, I need your confirmation in order to continue. 

See usage:

./check_zevenet_cpu.pl -H 192.168.100.123 -z myzapikey -c90:100 -w40:50
ZEVENET_CPU CRITICAL - Zevenet ADC Load Balancer CPU usage is 44.79 % (55.21 % idle) | Idle=55.21%;4050;90100 IOWait=0%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=32.29%;; Usage=44.79%;; User=12.5%;; Total=100%;;

**Comment by fantapereira** [comment] 2018-01-17 14:45
I got a different message now

[root@nagios libexec]# ./check_zevenet_cpu.pl  -H hostip -z MyZapiKey -c90:100 -w40:50
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at ./check_zevenet_cpu.pl line 216

**Comment by emiliocampos-zevenet** [comment] 2018-01-17 14:51
[check_zevenet_output.pl.zip](https://github.com/zevenet/zevenet-nagios-plugins/files/1639383/check_zevenet_output.pl.zip)

It seems like the output api is not as expected, so could you use the attached file check_zevenet_output.pl file with same input params than check_zevenet_cpu.pl and paste here the output for my review?

Thanks

**Comment by fantapereira** [comment] 2018-01-17 14:56
now i got only a quotation as output. 
`[root@nagios libexec]# ./check_zevenet_output.pl  -H hostip -z MyZapyKey-c90:100 -w40:50

''`

**Comment by emiliocampos-zevenet** [comment] 2018-01-17 16:53
It seem like or you didn't build properly the request, note that it requires a blank space after MyZapKey r
Or port 444 in load balancer is not reachable.

**Comment by fantapereira** [comment] 2018-01-17 18:15
there is an space between the zapi key and the warning option. I just deleted the complete key when i paste the info here.

![image](https://user-images.githubusercontent.com/31357915/35059215-34946d96-fb99-11e7-895c-89c93fc6e997.png)

**Comment by fantapereira** [comment] 2018-01-18 18:20
Hello @emiliocampos-zevenet did you have any update?

thanks

**Comment by emiliocampos-zevenet** [comment] 2018-01-19 08:18
Hi @fantapereira I would need you first check that the API works properly, please could you run a curl command to list cpu stats as follows?
https://www.zevenet.com/zapidocv3/#show-cpu-statistics

Thanks

**Comment by fantapereira** [comment] 2018-01-26 11:12
Hello Emilio, did you have any update on this?

**Comment by emiliocampos-zevenet** [comment] 2018-01-26 11:44
Hi, I can confirm that the checks work as expected, I am able to use them in a stretch debian server, it seems like the curl library of centos that you are working with is a little bit old so the behaviour seems different. 

As a workaround you could try to manage your the information in your latest comment, the used call to zapi is the used by the health check ./check_zevenet_cpu.pl

I would recommend you to update the curl library used in perl or If you do some troubleshooting to the script as soon you give me more information I could try to check it but as I said before the health check works properly so I am not able to reproduce your issue.

**Comment by fantapereira** [comment] 2018-01-26 11:55
All the libs are up to date:

Package libcurl-7.19.7-53.el6_9.x86_64 already installed and latest version
Nothing to do

`[root@nagios libexec]# rpm -qa | grep curl
python-pycurl-7.19.0-9.el6.x86_64

libcurl-7.19.7-53.el6_9.x86_64

curl-7.19.7-53.el6_9.x86_64

libcurl-devel-7.19.7-53.el6_9.x86_64

is there a newest version for curl?

**Comment by emiliocampos-zevenet** [comment] 2018-01-29 09:24
Hi, could you try the next?

1- Install the new module for monitoring:

perl -MCPAN -e 'install Monitoring::Plugin'

2- Change the 2 strings Nagios::Monitoring::Plugin  by Monitoring::Plugin ?

**Comment by emiliocampos-zevenet** [comment] 2018-02-01 16:53
Hi @fantapereira did you have the chance of checking my previous comment? Also a new pull have been commited thanks to @toxicvengeance so maybe it solves your issue. 

Please let us know just before to close the issue.

**Comment by emiliocampos-zevenet** [comment] 2018-02-13 13:03
@fantapereira did you solve the issue with latest commit we applied to the git?

**Comment by fantapereira** [comment] 2018-02-14 11:43
My deeply Apologizes, i was on vacations. I'll check and back to you shortly

**Comment by fantapereira** [comment] 2018-02-14 18:41
i followed your suggestion, downloaded the latest monitoring Module and also checked that Monitoring::Plugin was present. After installation still having the same error on line 179

[root@nagios libexec]# sudo perl check_zevenet_cpu.pl -H ServerIP -z ZAPIKEY -w 20 -c 10
Can't use an undefined value as filehandle reference at check_zevenet_cpu.pl line 179.

**Comment by fantapereira** [comment] 2018-02-15 19:25
I was finally managed to get this working. i installed the following packages manually

cpan -i YAML
cpan -i Test::CPAN::Meta
cpan -i Test::Pod::Coverage
cpan -i Test::Pod

then i logged in into CPAN and forced the installation

cpan[1]> force install WWW::Curl::Easy

after that i was able to get a proper response

`ZEVENET_CPU OK - Zevenet ADC Load Balancer CPU usage is 5.25 % (94.75 % idle) | Idle=94.75%;98;99 IOWait=0.12%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=0.25%;; Usage=5.25%;; User=4.88%;; Total=100%;;
`

Thanks for the patience :)

**Comment by emiliocampos-zevenet** [comment] 2018-02-15 19:38
Hi @fantapereira , thanks for confirmation, it seemed that the curl library for perl in your Centos was a little bit old. 

Regard

**Closed** 2018-02-15 19:38 UTC

**Comment by fantapereira** [comment] 2018-02-15 20:02
Sorry but how should i set the parameters?

if i choose -w 98 -c 99 i got the following output
ZEVENET_CPU CRITICAL - Zevenet ADC Load Balancer CPU usage is 0.12 % (99.88 % idle) | Idle=99.88%;98;99 IOWait=0%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=0%;; Usage=0.12%;; User=0.12%;; Total=100%;;

if i choose w2 -c1 i got the same Critical.
 -w 2 -c 1
ZEVENET_CPU CRITICAL - Zevenet ADC Load Balancer CPU usage is 0 % (100 % idle) | Idle=100%;2;1 IOWait=0%;; IRQ=0%;; Nice=0%;; SoftIRQ=0%;; Sys=0%;; Usage=0%;; User=0%;; Total=100%;;

**Comment by emiliocampos-zevenet** [comment] 2018-02-16 08:18
Dear @fantapereira  this issue has been closed because has been solved, please open a new issue with updated information about your new doubt and we'll be glad to help you.

Thanks!
